version: '3'

tasks:
  ############################################################
  default:
    desc: Run Build
    cmds:
      - task: web
      - task: server
      - task: cli

  ############################################################
  web:
    desc: Build Web App
    dir: web/start
    cmds:
      - npm install
      - npm run build

  ############################################################
  server:
    desc: Build Server
    cmds:
      - go build -o bin/server ./cmd/server/main.go

  ############################################################
  cli:
    desc: Build CLI
    cmds:
      - go build -o bin/cli ./cmd/cli/main.go

  ############################################################
  plugins:
    desc: Build Plugins
    cmds:
      - task: plugins:go_apiserver

  ############################################################
  plugins:go_apiserver:
    desc: Build go_apiserver plugin
    cmds:
      - go build -o bin/plugins/go_apiserver ./plugins/go_apiserver/
