version: '3'

tasks:
  ############################################################
  default:
    desc: Run Build
    cmds:
      - task: web
      - task: server
      - task: cli

  ############################################################
  web:
    desc: Build Web App
    dir: web/start
    cmds:
      - npm install
      - npm run build

  ############################################################
  server:
    desc: Build Server
    cmds:
      - go build -o bin/server ./cmd/server/main.go

  ############################################################
  cli:
    desc: Build CLI
    cmds:
      - go build -o bin/cli ./cmd/cli/main.go

  ############################################################
  plugins:
    desc: Build Plugins
    cmds:
      - task: plugins:go:apiserver

  ############################################################
  plugins:go:apiserver:
    desc: Build Plugins for Windows
    cmds:
      - >
        docker build \
          --build-arg SOURCE_DIR=plugins/go/apiserver \
          -t go-plugin-builder \
          -f build/Dockerfile.pluginbuild \
          .
      - >
        docker run --name temp-plugin-container go-plugin-builder
      - >
        docker cp temp-plugin-container:/app/plugin.so ./plugins/go/apiserver
      - >
        docker rm temp-plugin-container
