version: '3'

env:
  GOOS: "{{OS}}"

vars:
  GO_PACKAGE: github.com/zcubbs/power
  GO_PACKAGE_SHORT: power
  SCRIPTS_DIR: scripts
  PROTO_DIR: "proto"
  PROTO_GEN_DIR: "proto/gen"

includes:
  scan: .taskfiles/scan.yaml
  test: .taskfiles/test.yaml
  tls: .taskfiles/tls.yaml
  pb: .taskfiles/pb.yaml
  build: .taskfiles/build.yaml
  docker: .taskfiles/docker.yaml
  run: .taskfiles/run.yaml
  lint: .taskfiles/lint.yaml
  tools: .taskfiles/tools.yaml

tasks:
  default:
    cmd: task -l
