---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "this.name" . }}-storage-cm
data:
  config.json: |-
    {
      "identities": [
        {
          "name": "anonymous",
          "actions": [
            "Read:{{ .Values.storage.config.anonymousReadBucket }}"
          ]
        },
        {
          "name": "service_account",
          "credentials": [
            {
              "accessKey": "{{ .Values.storage.config.accessKey }}",
              "secretKey": "{{ .Values.storage.config.secretKey }}"
            }
          ],
          "actions": [
            "Admin",
            "Read",
            "ReadAcp",
            "List",
            "Tagging",
            "Write",
            "WriteAcp"
          ]
        }
      ]
    }
