apiVersion: v1
kind: Service
metadata:
  name: {{ include "this.name" . }}-storage
  labels:
    {{- include "this.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range .Values.storage.services}}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end}}
  selector:
    app.kubernetes.io/name: {{ include "this.name" . }}-storage
    app.kubernetes.io/instance: {{ .Release.Name }}
