apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "this.name" . }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "this.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/storage-cm.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "this.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}-server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            {{- range .Values.server.services }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
          startupProbe:
            httpGet:
              port: 8333
              path: /status
            initialDelaySeconds: 10
            periodSeconds: 5
          {{- if .Values.server.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.server.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.server.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.server.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          env:
            - name: S3_ENDPOINT
              value: localhost:8333
            {{- toYaml .Values.server.env | nindent 12 }}
        - name: {{ .Chart.Name }}-web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            {{- range .Values.web.services }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- if .Values.web.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.web.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.web.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.web.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          env:
            {{- toYaml .Values.web.env | nindent 12 }}
        - name: {{ .Chart.Name }}-storage
          image: "{{ .Values.storage.image }}"
          imagePullPolicy: {{ .Values.storage.pullPolicy }}
          args:
            - server
            - -s3
            - -s3.config=/config.json
            - -master.volumeSizeLimitMB={{ .Values.storage.volumeSizeLimitMB }}
          ports:
            {{- range .Values.storage.services }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- if .Values.storage.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.storage.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.storage.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.storage.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.storage.resources | nindent 12 }}
          env:
            {{- toYaml .Values.storage.env | nindent 12 }}
          volumeMounts:
            - mountPath: /config.json
              name: {{ .Chart.Name }}-storage-config
              subPath: config.json

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: {{ .Chart.Name }}-storage-config
          configMap:
            name: {{ .Chart.Name }}-storage-cm

      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8}}
