{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "this.name" . }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingressRoute.entryPoints | nindent 4 }}
  routes:
    {{- range .Values.server.services }}
    - match: {{ .match }}
      kind: Rule
      services:
        - name: {{ .name }}
          port: {{ .port }}
      # TODO: handle h2c
    {{- end}}
    {{- range .Values.web.services }}
    - match: {{ .match }}
      kind: Rule
      services:
        - name: {{ .name }}
          port: {{ .port }}
    {{- end}}
    {{- range .Values.storage.services }}
    - match: {{ .match }}
      kind: Rule
      services:
        - name: {{ .name }}
          port: {{ .port }}
    {{- end}}

{{- end }}
