version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-14T18-51-57Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      # URL for the MinIO server
      MINIO_SERVER_URL: https://minio.example.com
    command: server --console-address ":9011" /data
    ports:
      - "9010:9000" # minio
      - "9011:9011" # minio console
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
