apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "this.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "this.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "this.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "this.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      {{- if .Values.server.enablePlugins }}
      initContainers:
        - name: plugin-loader
          image: "{{ .Values.server.pluginImage.repository }}:{{ .Values.server.pluginImage.tag }}"
          imagePullPolicy: {{ .Values.server.pluginImage.pullPolicy }}
          command: ["/bin/sh", "-c", "cp -r /plugins/* {{ .Values.server.pluginDirectory.path }}"]
          volumeMounts:
            - name: plugin-volume
              mountPath: "{{ .Values.server.pluginDirectory.path }}"
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            {{- range .Values.server.services }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- if .Values.server.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.server.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.server.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.server.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          env:
            {{- toYaml .Values.server.env | nindent 12 }}
            {{- if not (include "chart.containsKey" (list .Values.server.env "S3_ENDPOINT")) }}
            - name: S3_ENDPOINT
              value: {{ include "this.name" . }}-storage:8333
            {{- end }}
            {{- if .Values.server.enablePlugins }}
            - name: BLUEPRINT_ENABLE_PLUGINS
              value: "true"
            - name: BLUEPRINT_PLUGIN_DIR
              value: "/plugins"
            {{- end }}
          {{- if .Values.server.enablePlugins }}
          volumeMounts:
            - name: plugin-volume
              mountPath: /plugins
          {{- end }}
        - name: {{ .Chart.Name }}-web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            {{- range .Values.web.services }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- if .Values.web.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.web.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.web.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.web.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          env:
            {{- toYaml .Values.web.env | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: plugin-volume
          emptyDir: { }

      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8}}
